{% set version = '0.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shiny.react
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shiny.react_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shiny.react/shiny.react_{{ version }}.tar.gz
  sha256: 507477cd7ff35f06df6c433d48320100c03f1fcc8311b2b4bc0c13d0c1149b68

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
    - r-htmltools
    - r-jsonlite
    - r-logger
    - r-purrr
    - r-rlang
    - r-shiny
  run:
    - r-base
    - r-glue
    - r-htmltools
    - r-jsonlite
    - r-logger
    - r-purrr
    - r-rlang
    - r-shiny

test:
  commands:
    - $R -e "library('shiny.react')"           # [not win]
    - "\"%R%\" -e \"library('shiny.react')\""  # [win]

about:
  home: https://appsilon.github.io/shiny.react/, https://github.com/Appsilon/shiny.react
  license: LGPL-3.0-only
  summary: A toolbox for defining React component wrappers which can be used seamlessly in Shiny
    apps.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
